### ISSUE TITLE
Nightly build with Travis CI or GitLab CI

### ISSUE THREAD

**Issue by liuqun** [lhelontra/tensorflow-on-arm#17]
Add a configuration file `.travis.yml` and let Travis CI build all the packages for us automatically.

For example: https://travis-ci.org/liuqun/tensorflow-on-arm/builds/405622115

```
sudo: required
services:
  - docker
language: bash
install:
  - docker run --rm hello-world
script:
  - echo "Done!"
```
https://github.com/liuqun/tensorflow-on-arm/commit/9f617a659691e6b14249494b996bddd5ed3d620d

**Comment by lhelontra** [comment]
Hi, 
Good advice, i'm will be write a travis configuration file soon.

**Comment by liuqun** [comment]
@lhelontra Here is a quick solution: https://github.com/liuqun/tensorflow-on-arm/tree/build-using-docker
You may try and see whether it works for you.

**Comment by liuqun** [comment]
Travis CI report:
```
The job exceeded the maximum time limit for jobs, and has been terminated. 
```

**Comment by liuqun** [comment]
Here is one improved solution.
```
# File: .travis.yml
sudo: required
services:
  - docker
language: bash
env:
  global:
    - PREBUILT_DOCKER_IMAGE=daocloud.io/liuqun1986/tensorflow-on-arm:latest
  matrix:
    - TARGET_NAME=rpi
    - TARGET_NAME=rpi_one
    - TARGET_NAME=rpi_one_openblas
    - TARGET_NAME=odroidc1
    - TARGET_NAME=odroidc2
    - TARGET_NAME=beagle_black
install:
  - mkdir -p $TARGET_NAME
script:
script:
  - docker run --rm -v $TRAVIS_BUILD_DIR/$TARGET_NAME:/tmp -v $TRAVIS_BUILD_DIR/build_tensorflow:/root $PREBUILT_DOCKER_IMAGE /root/build_tensorflow.sh /root/configs/$TARGET_NAME.conf
```
https://travis-ci.org/liuqun/tensorflow-on-arm/builds/407034818
https://github.com/liuqun/tensorflow-on-arm/tree/travis-ci

But I was still worrying about the time limit in Travis-CI's free of charge version.

The build [log.txt](https://api.travis-ci.org/v3/job/407034819/log.txt) said: `The job exceeded the maximum time limit for jobs, and has been terminated.`

Maybe my script could work in its commercial($129 per month) or educational version.

Any suggestion?
